"""Add battles table

Revision ID: e64ccb561367
Revises: 0227c478fad6
Create Date: 2026-02-06 10:33:29.395919

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e64ccb561367'
down_revision = '0227c478fad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1_trainer_id', sa.Integer(), nullable=False),
    sa.Column('team2_trainer_id', sa.Integer(), nullable=False),
    sa.Column('winner_trainer_id', sa.Integer(), nullable=False),
    sa.Column('team1_strength', sa.Float(), nullable=False),
    sa.Column('team2_strength', sa.Float(), nullable=False),
    sa.Column('victory_margin', sa.Float(), nullable=False),
    sa.Column('battle_date', sa.DateTime(), nullable=False),
    sa.Column('battle_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team1_trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['team2_trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['winner_trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_battle_date'), 'battles', ['battle_date'], unique=False)
    op.create_index(op.f('ix_battles_team1_trainer_id'), 'battles', ['team1_trainer_id'], unique=False)
    op.create_index(op.f('ix_battles_team2_trainer_id'), 'battles', ['team2_trainer_id'], unique=False)
    op.create_index(op.f('ix_battles_winner_trainer_id'), 'battles', ['winner_trainer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_battles_winner_trainer_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_team2_trainer_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_team1_trainer_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_battle_date'), table_name='battles')
    op.drop_table('battles')
    # ### end Alembic commands ###
