"""initial migration

Revision ID: 0227c478fad6
Revises:
Create Date: 2026-02-02 10:36:19.375631

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '0227c478fad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_type'), 'items', ['type'], unique=False)
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type_primary', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('type_secondary', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('attacks', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nature', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    op.create_index(op.f('ix_pokemon_nature'), 'pokemon', ['nature'], unique=False)
    op.create_index(op.f('ix_pokemon_type_primary'), 'pokemon', ['type_primary'], unique=False)
    op.create_index(op.f('ix_pokemon_type_secondary'), 'pokemon', ['type_secondary'], unique=False)
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainers_name'), 'trainers', ['name'], unique=False)
    op.create_index(op.f('ix_trainers_region'), 'trainers', ['region'], unique=False)
    op.create_table('backpacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backpacks_item_id'), 'backpacks', ['item_id'], unique=False)
    op.create_index(op.f('ix_backpacks_trainer_id'), 'backpacks', ['trainer_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_pokemon_id'), 'teams', ['pokemon_id'], unique=False)
    op.create_index(op.f('ix_teams_trainer_id'), 'teams', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_trainer_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_pokemon_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_backpacks_trainer_id'), table_name='backpacks')
    op.drop_index(op.f('ix_backpacks_item_id'), table_name='backpacks')
    op.drop_table('backpacks')
    op.drop_index(op.f('ix_trainers_region'), table_name='trainers')
    op.drop_index(op.f('ix_trainers_name'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_pokemon_type_secondary'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_type_primary'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_nature'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_items_type'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
